"""
ComfyUI Veilance Nodes
Custom nodes including model loading, resolution, and prompt selector functionality.
"""

from importlib import import_module

from .resolution_selector import (
    NODE_CLASS_MAPPINGS as RESOLUTION_SELECTOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_SELECTOR_DISPLAY_MAPPINGS,
)
from .prompt_selector import (
    NODE_CLASS_MAPPINGS as PROMPT_SELECTOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_SELECTOR_DISPLAY_MAPPINGS,
)
from .model_loader_trio import (
    NODE_CLASS_MAPPINGS as MODEL_LOADER_TRIO_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MODEL_LOADER_TRIO_DISPLAY_MAPPINGS,
)
from .model_loader_checkpoint_vae import (
    NODE_CLASS_MAPPINGS as MODEL_LOADER_CHECKPOINT_VAE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MODEL_LOADER_CHECKPOINT_VAE_DISPLAY_MAPPINGS,
)
from .prompt_cleaner import (
    NODE_CLASS_MAPPINGS as PROMPT_CLEANER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_CLEANER_DISPLAY_MAPPINGS,
)
from .pipe_ksampler import (
    NODE_CLASS_MAPPINGS as PIPE_KSAMPLER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PIPE_KSAMPLER_DISPLAY_MAPPINGS,
)
from .pipe_builder import (
    NODE_CLASS_MAPPINGS as PIPE_BUILDER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PIPE_BUILDER_DISPLAY_MAPPINGS,
)
from .pipe_router import (
    NODE_CLASS_MAPPINGS as PIPE_ROUTER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PIPE_ROUTER_DISPLAY_MAPPINGS,
)
from .sampler_presets import (
    NODE_CLASS_MAPPINGS as SAMPLER_PRESETS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_PRESETS_DISPLAY_MAPPINGS,
)
from .seed_strategy import (
    NODE_CLASS_MAPPINGS as SEED_STRATEGY_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEED_STRATEGY_DISPLAY_MAPPINGS,
)
from .lora_stack import (
    NODE_CLASS_MAPPINGS as LORA_STACK_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_STACK_DISPLAY_MAPPINGS,
)
from .nano_gpt import (
    NODE_CLASS_MAPPINGS as NANO_GPT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NANO_GPT_DISPLAY_MAPPINGS,
)


def _load_optional_node_package(module_name: str):
    try:
        module = import_module(f".{module_name}", __name__)
    except Exception as exc:
        print(
            f"[ComfyUI-Veilance-Nodes] Skipping optional package '{module_name}' "
            f"because it failed to import: {exc}"
        )
        return {}, {}

    return (
        getattr(module, "NODE_CLASS_MAPPINGS", {}),
        getattr(module, "NODE_DISPLAY_NAME_MAPPINGS", {}),
    )


SAVE_IMAGE_CIVITAI_MAPPINGS, SAVE_IMAGE_CIVITAI_DISPLAY_MAPPINGS = _load_optional_node_package(
    "save_image_civitai"
)
IMAGE_SHARPEN_MAPPINGS, IMAGE_SHARPEN_DISPLAY_MAPPINGS = _load_optional_node_package(
    "image_sharpen"
)
FILM_GRAIN_MAPPINGS, FILM_GRAIN_DISPLAY_MAPPINGS = _load_optional_node_package(
    "film_grain"
)

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **RESOLUTION_SELECTOR_MAPPINGS,
    **PROMPT_SELECTOR_MAPPINGS,
    **MODEL_LOADER_TRIO_MAPPINGS,
    **MODEL_LOADER_CHECKPOINT_VAE_MAPPINGS,
    **PROMPT_CLEANER_MAPPINGS,
    **PIPE_KSAMPLER_MAPPINGS,
    **PIPE_BUILDER_MAPPINGS,
    **PIPE_ROUTER_MAPPINGS,
    **SAMPLER_PRESETS_MAPPINGS,
    **SEED_STRATEGY_MAPPINGS,
    **LORA_STACK_MAPPINGS,
    **NANO_GPT_MAPPINGS,
    **SAVE_IMAGE_CIVITAI_MAPPINGS,
    **IMAGE_SHARPEN_MAPPINGS,
    **FILM_GRAIN_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RESOLUTION_SELECTOR_DISPLAY_MAPPINGS,
    **PROMPT_SELECTOR_DISPLAY_MAPPINGS,
    **MODEL_LOADER_TRIO_DISPLAY_MAPPINGS,
    **MODEL_LOADER_CHECKPOINT_VAE_DISPLAY_MAPPINGS,
    **PROMPT_CLEANER_DISPLAY_MAPPINGS,
    **PIPE_KSAMPLER_DISPLAY_MAPPINGS,
    **PIPE_BUILDER_DISPLAY_MAPPINGS,
    **PIPE_ROUTER_DISPLAY_MAPPINGS,
    **SAMPLER_PRESETS_DISPLAY_MAPPINGS,
    **SEED_STRATEGY_DISPLAY_MAPPINGS,
    **LORA_STACK_DISPLAY_MAPPINGS,
    **NANO_GPT_DISPLAY_MAPPINGS,
    **SAVE_IMAGE_CIVITAI_DISPLAY_MAPPINGS,
    **IMAGE_SHARPEN_DISPLAY_MAPPINGS,
    **FILM_GRAIN_DISPLAY_MAPPINGS,
}

# JavaScript extensions directory
WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

